### ISSUE TITLE
Can't upgrade to 2.8.10?

### ISSUE THREAD

**Issue by menloperk** [leeyuentuen/alfen_wallbox#148]
Getting this error message...

Failed to perform the action update/install. The version 2.8.10 for this integration can not be used with HACS.

**Comment by leeyuentuen** [comment]
2.8.10 is a beta version

**Comment by TeddyTBP** [comment]
SAme here in HACS 2.0.1 there is no more Beta slider but if i select PRE-Release it tels me its not compatible with HACS

**Comment by TeddyTBP** [comment]
![image](https://github.com/user-attachments/assets/c2fa0154-95d2-4042-83b3-e2a3ccd11aad)

**Comment by menloperk** [comment]
Any solution to this as this new HACS UI is completely confusing...

**Comment by leeyuentuen** [comment]
i haven't got the issue on it. maybe try remove them and redownload them?

**Comment by petepall** [comment]
Having same issue. Can’t install the pre release or can’t downgrade to earlier version that does not have the update issues.
HACS keeps giving the message as show in the screenshot shown earlier.

I did remove the whole setup and reinstalled the integration but that did not resolve the issue.

**Comment by leeyuentuen** [comment]
do you see something in log?
have you install hacs?

**Comment by petepall** [comment]
@leeyuentuen yes I have HACS running

I’m seeing the following in the logs

`2024-10-03 21:41:07.092 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0xffff6dff1fd0>, <Purpose.SERVER_AUTH: _ASN1Object(nid=129, shortname='serverAuth', longname='TLS Web Server Authentication', oid='1.3.6.1.5.5.7.3.1')>) inside the event loop by custom integration 'alfen_wallbox' at custom_components/alfen_wallbox/alfen.py, line 97: context = ssl.create_default_context() (offender: /usr/local/lib/python3.12/ssl.py, line 713: context.load_default_certs(purpose)), please report it to the author of the 'alfen_wallbox' custom integration
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 556, in start
task = asyncio.Task(coro, loop=loop, eager_start=True)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
return await handler(request)
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
response = await handler(request)
File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
result = await handler(request, **request.match_info)
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
return await func(self, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
return await method(view, request, data, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 370, in async_configure
result = await self._async_configure(flow_id, user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 417, in _async_configure
result = await self._async_handle_step(
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 520, in _async_handle_step
result: _FlowResultT = await getattr(flow, method)(user_input)
File "/config/custom_components/alfen_wallbox/config_flow.py", line 77, in async_step_user
return await self._create_device(user_input[CONF_HOST], user_input[CONF_NAME], user_input[CONF_USERNAME], user_input[CONF_PASSWORD], user_input[CONF_SCAN_INTERVAL])
File "/config/custom_components/alfen_wallbox/config_flow.py", line 44, in _create_device
device = AlfenDevice(
File "/config/custom_components/alfen_wallbox/alfen.py", line 97, in __init__
context = ssl.create_default_context()
2024-10-03 21:41:38.831 WARNING (MainThread) [homeassistant.components.sensor] Updating alfen_wallbox sensor took longer than the scheduled update interval 0:00:05
2024-10-03 21:41:43.832 WARNING (MainThread) [homeassistant.components.sensor] Updating alfen_wallbox sensor took longer than the scheduled update interval 0:00:05
2024-10-03 21:41:43.901 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.wallbox is taking over 10 seconds `

**Comment by petepall** [comment]
Also getting allot of logs related to the sensors taking over 10 seconde so I was trying to install an earlier version

**Comment by leeyuentuen** [comment]
> Also getting allot of logs related to the sensors taking over 10 seconde so I was trying to install an earlier version

this is normal. on first boot he need read all the logs of the transaction

**Comment by leeyuentuen** [comment]
> @leeyuentuen yes I have HACS running
> 
> I’m seeing the following in the logs
> 
> `2024-10-03 21:41:07.092 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0xffff6dff1fd0>, <Purpose.SERVER_AUTH: _ASN1Object(nid=129, shortname='serverAuth', longname='TLS Web Server Authentication', oid='1.3.6.1.5.5.7.3.1')>) inside the event loop by custom integration 'alfen_wallbox' at custom_components/alfen_wallbox/alfen.py, line 97: context = ssl.create_default_context() (offender: /usr/local/lib/python3.12/ssl.py, line 713: context.load_default_certs(purpose)), please report it to the author of the 'alfen_wallbox' custom integration For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 556, in start task = asyncio.Task(coro, loop=loop, eager_start=True) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request resp = await request_handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle return await handler(request) File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware return await handler(request) File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware response = await handler(request) File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle result = await handler(request, **request.match_info) File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin return await func(self, request, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post return await super().post(request, flow_id) File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper return await method(view, request, data, *args, **kwargs) File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post result = await self._flow_mgr.async_configure(flow_id, data) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 370, in async_configure result = await self._async_configure(flow_id, user_input) File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 417, in _async_configure result = await self._async_handle_step( File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 520, in _async_handle_step result: _FlowResultT = await getattr(flow, method)(user_input) File "/config/custom_components/alfen_wallbox/config_flow.py", line 77, in async_step_user return await self._create_device(user_input[CONF_HOST], user_input[CONF_NAME], user_input[CONF_USERNAME], user_input[CONF_PASSWORD], user_input[CONF_SCAN_INTERVAL]) File "/config/custom_components/alfen_wallbox/config_flow.py", line 44, in _create_device device = AlfenDevice( File "/config/custom_components/alfen_wallbox/alfen.py", line 97, in __init__ context = ssl.create_default_context() 2024-10-03 21:41:38.831 WARNING (MainThread) [homeassistant.components.sensor] Updating alfen_wallbox sensor took longer than the scheduled update interval 0:00:05 2024-10-03 21:41:43.832 WARNING (MainThread) [homeassistant.components.sensor] Updating alfen_wallbox sensor took longer than the scheduled update interval 0:00:05 2024-10-03 21:41:43.901 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.wallbox is taking over 10 seconds `

what do you mean with reinstall whole of them? you install home assistant from clean install or just the alfen component only?

**Comment by petepall** [comment]
But strange is that I can’t make changes that worked before like setting the charging power or even the API logout is not reacting. If I want to logout the API I now need to stop the integration and HACS version changes are not working

I just tried to load a different version and now see the following in the logs

![IMG_1992](https://github.com/user-attachments/assets/9480978d-73d6-4185-8ff6-5eee20e74757)
![IMG_1991](https://github.com/user-attachments/assets/477784d8-8678-4658-a2ae-8d8e75c7ec8b)

**Comment by petepall** [comment]
> what do you mean with reinstall whole of them? you install home assistant from clean install or just the alfen component only?

I removed the Alfen integration from my home assistant and than tried to add version 2.7.29 but this does not work. Neither could I add 2.8.10 to test that one

**Comment by petepall** [comment]
I’m also seeing allot of warnings in the alfen logs. If I stop the integration in home assistant than these warnings stop being reported in the alfen logs.

![IMG_1990](https://github.com/user-attachments/assets/bb268488-2c4b-41e9-9b55-4d4410a05088)

**Comment by petepall** [comment]
this is my current Alfen log. Once I stoppen the HA integration the warnings stooped

![IMG_1993](https://github.com/user-attachments/assets/5434ee95-d632-41e3-a5ef-ff9c756e5370)

**Comment by Mr-Star-Lord** [comment]
@petepall I accidentally updated HACS and the Alfen Wallbox integration and got the same issue as you have: no updates on entities. This happened before and downgrade to 2.7.29 worked, but as you mentioned with the new HACS, you cannot downgrade to 2.7.29.

I solved this by downloading 2.7.29 manually, renamed the folder "alfen_wallbox" in "/config/custom_components/" to "alfen_wallbox_OLD" and copied the folder "alfen_wallbox" from the 2.7.29 download to the "/config/custom_components/" folder.

Reboot of HA and all sensors are updating again.

**Comment by menloperk** [comment]
This is still broken. You can't download a prerelease with HACS. It throws an error:
The version 2.8.10 for this integration can not be used with HACS.
I can't flip a switch as the integration is not working due to another error!

**Comment by Mr-Star-Lord** [comment]
> This is still broken. You can't download a prerelease with HACS. It throws an error:
> The version 2.8.10 for this integration can not be used with HACS.
> I can't flip a switch as the integration is not working due to another error #152 !

The best way is to install it manually then. If you use the same way as I did (see above) you should be able to run another release without HACS.

**Comment by leeyuentuen** [comment]
check latest release, if issue still exists, open a new issue on it with more information which version you are now running.
