### ISSUE TITLE
Some data not updating. Roll-back not possible

### ISSUE THREAD

**Issue by WimBra** [leeyuentuen/alfen_wallbox#166]
Some of the entities are not updating anymore.

*Main active max current socket 1     (cat. generic)
*Uptime     (cat. generic)

Also (don't know if it was before) when I try to configure the integration... A error appears 
"Error, config flow could not be loaded. 500 internal server error got itself in trouble"

I tried a roll-back... but unfortunatly "not possible with version of hacks".

**Comment by slingshot74** [comment]
Same issue here, unfortunately not possible to rollback to previous version

**Comment by leeyuentuen** [comment]
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.9.2-beta

Nothing changed yet, but let me know if still exists

**Comment by WimBra** [comment]
The version 2.9.2-beta for this integration can not be used with HACS.

**Comment by WimBra** [comment]
For the moment the integration itself works...
Online a few bugs that can be fixed later.

Just enjoy the holidays, we will adress the problems later 😉

**Comment by leeyuentuen** [comment]
Maybe check this:
https://github.com/leeyuentuen/alfen_wallbox/issues/148#issuecomment-2460015325

![Screenshot_2024-12-24-22-19-19-09_c3a231c25ed346e59462e84656a70e50~2](https://github.com/user-attachments/assets/3971f014-0014-4315-b527-5d48bbfbd49c)

**Comment by WimBra** [comment]
enabled "pre-releases" and updated to 2.9.2
no more connection to charger "error connecting api"
![api](https://github.com/user-attachments/assets/b94a1f63-1992-42fa-8be1-9b483b385bc7)

roll-back on any versions still not possible

**Comment by WimBra** [comment]
connection came back after 20minutes

**Comment by WimBra** [comment]
I've updated my HA to 2024.12.5 (I came from 2024.11.2)
now I don't have the problem anymore of the "500 internal server error"

maybe a notice that 2024.12 version is needed???

after many retry's and re-configure of the integration, data is coming back into HA.
I had a lot of TLS issues.

for the moment it is working, but a restart of HA would kill the connection again.

**Comment by sven-debug** [comment]
For all the guys that have problems with the integration: 

- First delete the current Alfen Wallbox Integration (the broken one) 
- Reboot Home Assistant
- Download the version 2.8.9. from the upper right code button an save the zip-file. 
- Unpack it and transfer the content underneath custom_components into your custom components folder
- Reboot Home Assistant

This worked for me.
- Connect

Best regards
Sven

**Comment by WimBra** [comment]
> For all the guys that have problems with the integration:
> 
> * First delete the current Alfen Wallbox Integration (the broken one)
> * Reboot Home Assistant
> * Download the version 2.8.9. from the upper right code button an save the zip-file.
> * Unpack it and transfer the content underneath custom_components into your custom components folder
> * Reboot Home Assistant
> 
> This worked for me.
> 
> * Connect
> 
> Best regards Sven

Tnx... that roll-back method worked fine for me.
I'll wait for new release with api stability

**Comment by slingshot74** [comment]
Hi,

Do the entity names stay the dames this way?

Op wo 25 dec 2024 16:02 schreef WimBra ***@***.***>:

**Comment by sven-debug** [comment]
The names might be the same, the entity ID‘s changed in my case.

BR
Sven
Am 25. Dez. 2024, 16:05 +0100 schrieb slingshot74 ***@***.***>:

**Comment by WimBra** [comment]
My ID's are the same (I guess as long if you use exact the same name)

all previous data is not lost.
![api](https://github.com/user-attachments/assets/a5039d8d-314d-4f66-8b02-efdf517462c4)
red: all the api troubles with 2.9.2
green: roll-back with sven-method

no data is lost.

**Comment by slingshot74** [comment]
> Maybe check this: [#148 (comment)](https://github.com/leeyuentuen/alfen_wallbox/issues/148#issuecomment-2460015325)
> 
> ![Screenshot_2024-12-24-22-19-19-09_c3a231c25ed346e59462e84656a70e50~2](https://private-user-images.githubusercontent.com/1487966/398483439-3971f014-0014-4315-b527-5d48bbfbd49c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMDU2NTcsIm5iZiI6MTczNTIwNTM1NywicGF0aCI6Ii8xNDg3OTY2LzM5ODQ4MzQzOS0zOTcxZjAxNC0wMDE0LTQzMTUtYjUyNy01ZDQ4YmJmYmQ0OWMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjZUMDkyOTE3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTc5OWZhNzk5MDBlZWEwOTVhNjE2MWI1NDc0NmUxMDRmZGFjZDRkNjg4MjQyYjM0MTY3ZjZiOTA4MDhmMTljOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.m4_-_PKY6n5KMPl6LZfYILV8QaFy-_98U1MjctDkLJ0)

Where can I see / set this information. 
I don't see it.

**Comment by slingshot74** [comment]
I have updated to version 2.9.2. 
The problem is still there, no update on the transactions.

**Comment by TomDP** [comment]
I used the MyEve and updated the firmware of the charging station from V5 to V6 and that fixed it for me.

**Comment by slingshot74** [comment]
I was already on 6.x for the single pro version. But have the issue.
When I used the 7 x version I didn't get the transactions anymore. This is
a bug in the 7 version and will be fixed with new version of the firmware.
I had a support call will Alfen for that.

Op do 26 dec 2024 18:07 schreef TomDP ***@***.***>:

**Comment by leeyuentuen** [comment]
I have new beta 2 and beta 3

Can you manual try install them in custom_component and see of the problem solved?

**Comment by WimBra** [comment]
Both beta’s gave the same problem

Afterwards I even had to remove and re-initialise the wallbox again in HA to complete the roll-back to 2.8.9




 

Van: Tuen Lee ***@***.***> 
Verzonden: maandag 30 december 2024 23:01
Aan: leeyuentuen/alfen_wallbox ***@***.***>
CC: WimBra ***@***.***>; Author ***@***.***>
Onderwerp: Re: [leeyuentuen/alfen_wallbox] Some data not updating. Roll-back not possible (Issue #166)

 

I have new beta 2 and beta 3

Can you manual try install them in custom_component and see of the problem solved?

**Comment by WimBra** [comment]
> Both beta’s gave the same problem "error communicating with api" Afterwards I even had to remove and re-initialise the wallbox again in HA to complete the roll-back to 2.8.9

Debug file:
```
2024-12-30 23:55:12.003 DEBUG (MainThread) [custom_components.alfen_wallbox.coordinator] Connection to 192.168.50.233 timed out
2024-12-30 23:55:24.172 DEBUG (MainThread) [custom_components.alfen_wallbox.alfen] Response <ClientResponse(https://192.168.50.233/api/info) [200 OK ]>
<CIMultiDictProxy('Content-Type': 'alfen/json; charset=UTF-8', 'Connection': 'keep-alive', 'Content-Length': '215', 'Version': '1')>

2024-12-30 23:55:42.396 DEBUG (MainThread) [custom_components.alfen_wallbox.coordinator] Connection to 192.168.50.233 timed out
```

**Comment by leeyuentuen** [comment]
> > Both beta’s gave the same problem "error communicating with api" Afterwards I even had to remove and re-initialise the wallbox again in HA to complete the roll-back to 2.8.9
> 
> Debug file:
> 
> ```
> 2024-12-30 23:55:12.003 DEBUG (MainThread) [custom_components.alfen_wallbox.coordinator] Connection to 192.168.50.233 timed out
> 2024-12-30 23:55:24.172 DEBUG (MainThread) [custom_components.alfen_wallbox.alfen] Response <ClientResponse(https://192.168.50.233/api/info) [200 OK ]>
> <CIMultiDictProxy('Content-Type': 'alfen/json; charset=UTF-8', 'Connection': 'keep-alive', 'Content-Length': '215', 'Version': '1')>
> 
> 2024-12-30 23:55:42.396 DEBUG (MainThread) [custom_components.alfen_wallbox.coordinator] Connection to 192.168.50.233 timed out
> ```

Did you fetch transaction?

**Comment by WimBra** [comment]
> > > Both beta’s gave the same problem "error communicating with api" Afterwards I even had to remove and re-initialise the wallbox again in HA to complete the roll-back to 2.8.9
> > 
> > 
> > Debug file:
> > ```
> > 2024-12-30 23:55:12.003 DEBUG (MainThread) [custom_components.alfen_wallbox.coordinator] Connection to 192.168.50.233 timed out
> > 2024-12-30 23:55:24.172 DEBUG (MainThread) [custom_components.alfen_wallbox.alfen] Response <ClientResponse(https://192.168.50.233/api/info) [200 OK ]>
> > <CIMultiDictProxy('Content-Type': 'alfen/json; charset=UTF-8', 'Connection': 'keep-alive', 'Content-Length': '215', 'Version': '1')>
> > 
> > 2024-12-30 23:55:42.396 DEBUG (MainThread) [custom_components.alfen_wallbox.coordinator] Connection to 192.168.50.233 timed out
> > ```
> 
> Did you fetch transaction?

did you mean the log of the charger?
```
2014-05-15T00:34:26.109Z:WARNING:taskWebClient.c:234:Client (fd=3) disconnected (r: -0x7880)
2014-05-15T00:34:26.117Z:INFO:taskWebClient.c:166:Removing previously connected client
2014-05-15T00:34:26.156Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2014-05-15T00:34:26.183Z:WARNING:taskWebClient.c:812:TLS handshake failed (-0x50) for fd=3
2014-05-15T00:34:26.191Z:WARNING:taskWebClient.c:836:Failed to setup WebClient -80
2014-05-15T00:34:27.980Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2014-05-15T00:34:58.097Z:WARNING:taskWebClient.c:234:Client (fd=3) disconnected (r: -0x7880)
2014-05-15T00:34:58.109Z:INFO:taskWebClient.c:166:Removing previously connected client
2014-05-15T00:34:58.164Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2014-05-15T00:34:58.187Z:WARNING:taskWebClient.c:812:TLS handshake failed (-0x50) for fd=3
2014-05-15T00:34:58.199Z:WARNING:taskWebClient.c:836:Failed to setup WebClient -80
2014-05-15T00:34:59.906Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2014-05-15T00:35:30.101Z:WARNING:taskWebClient.c:234:Client (fd=3) disconnected (r: -0x7880)
2014-05-15T00:35:30.113Z:INFO:taskWebClient.c:166:Removing previously connected client
2014-05-15T00:35:30.187Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2014-05-15T00:35:30.210Z:WARNING:taskWebClient.c:812:TLS handshake failed (-0x50) for fd=3
2014-05-15T00:35:30.222Z:WARNING:taskWebClient.c:836:Failed to setup WebClient -80
2014-05-15T00:35:36.078Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2014-05-15T00:36:02.097Z:WARNING:taskWebClient.c:234:Client (fd=3) disconnected (r: -0x7880)
2014-05-15T00:36:02.105Z:INFO:taskWebClient.c:166:Removing previously connected client
2014-05-15T00:36:02.179Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2014-05-15T00:36:02.207Z:WARNING:taskWebClient.c:812:TLS handshake failed (-0x50) for fd=3
2014-05-15T00:36:02.214Z:WARNING:taskWebClient.c:836:Failed to setup WebClient -80
2014-05-15T00:36:36.527Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2014-05-15T00:36:51.937Z:WARNING:taskWebClient.c:234:Client (fd=3) disconnected (r: -0x0)
2014-05-15T00:36:51.945Z:INFO:taskWebClient.c:166:Removing previously connected client
2014-05-15T00:36:51.964Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2014-05-15T00:36:51.992Z:WARNING:taskWebClient.c:812:TLS handshake failed (-0x50) for fd=3
2014-05-15T00:36:52.000Z:WARNING:taskWebClient.c:836:Failed to setup WebClient -80
2014-05-15T00:38:48.367Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2014-05-15T00:39:07.656Z:WARNING:taskWebClient.c:234:Client (fd=3) disconnected (r: -0x7880)
2014-05-15T00:39:07.667Z:INFO:taskWebClient.c:166:Removing previously connected client
2014-05-15T00:39:07.769Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2014-05-15T00:39:07.796Z:WARNING:taskWebClient.c:812:TLS handshake failed (-0x50) for fd=3
2014-05-15T00:39:07.804Z:WARNING:taskWebClient.c:836:Failed to setup WebClient -80
2014-05-15T00:39:09.527Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2014-05-15T00:39:29.078Z:WARNING:taskWebClient.c:234:Client (fd=3) disconnected (r: -0x7880)
2014-05-15T00:39:29.089Z:INFO:taskWebClient.c:166:Removing previously connected client
2014-05-15T00:39:29.128Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2014-05-15T00:39:29.156Z:WARNING:taskWebClient.c:812:TLS handshake failed (-0x50) for fd=3
2014-05-15T00:39:29.164Z:WARNING:taskWebClient.c:836:Failed to setup WebClient -80
2014-05-15T00:39:39.835Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2014-05-15T00:39:56.796Z:INFO:taskCANopen.c:1065:Persistent memory hash changed
2014-05-15T00:39:57.078Z:INFO:taskCANopen.c:1767:Updated object 0x21b6,   8 bytes
2014-05-15T00:40:01.078Z:WARNING:taskWebClient.c:234:Client (fd=3) disconnected (r: -0x7880)
2014-05-15T00:40:01.085Z:INFO:taskWebClient.c:166:Removing previously connected client
2014-05-15T00:40:01.101Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2014-05-15T00:40:01.128Z:WARNING:taskWebClient.c:812:TLS handshake failed (-0x50) for fd=3
2014-05-15T00:40:01.136Z:WARNING:taskWebClient.c:836:Failed to setup WebClient -80
2014-05-15T00:40:04.746Z:INFO:heap_trace.c:493:free: 90616/160768 (56.4%) min: 65696 (40.9%) alloc #: 168
2014-05-15T00:40:04.757Z:INFO:heap_trace.c:495:fragm: 22.1% 4K:  9.6% free blocks: # 10 largest: 70560
2014-05-15T00:40:11.792Z:INFO:active_lb.c:308:SMt:(0.0 0.0 0.0)A Free:(32.0 32.0 32.0)A ALB:(0.0 0.0 0.0)A
2014-05-15T00:41:54.437Z:USER:taskMaster.c:6147:Socket #1: L1N=231.5V L2N=0.0V L3N=0.0V L1L2=n/a L2L3=n/a L3L1=n/a 
2014-05-15T00:41:54.453Z:USER:taskMaster.c:6183:Socket #1: I1=0.0A I2=0.0A I3=0.0A P=0.0kW Idc=0.6mA
2014-05-15T00:42:59.460Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2014-05-15T00:43:10.066Z:WARNING:taskWebClient.c:234:Client (fd=3) disconnected (r: -0x7880)
2014-05-15T00:43:10.074Z:INFO:taskWebClient.c:166:Removing previously connected client
2014-05-15T00:43:10.156Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2014-05-15T00:43:11.878Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2014-05-15T00:43:12.000Z:SECURITY:taskWebClient.c:448:Received unauthorized request, so removing client
2014-05-15T00:43:12.011Z:INFO:taskWebClient.c:166:Removing previously connected client
2014-05-15T00:43:12.121Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2014-05-15T00:43:13.843Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2014-05-15T00:43:14.144Z:SECURITY:httpd_login.c:155:WebClient ha connected (account: admin)
```

PS, I just noticed the system time of the charger is way off... I will change it.

**Comment by leeyuentuen** [comment]
I mean if you have select transaction to fetch all the log from the alfen wallbox.

Normally the beta 2

**Comment by WimBra** [comment]
ok I'll re-install the beta 2 and wait 5 minutes

**Comment by WimBra** [comment]
did a http logout
shutdown HA, waited 10 minutes.
installed beta2
Startup HA

same problem. could not connect api
removed the device and reinstalled the device in HA.
"could not initialize.
stopped HA and the container log gave this error:
```
2024-12-31 10:43:58.330 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 192.168.50.233 for alfen_wallbox
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 640, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alfen_wallbox/__init__.py", line 80, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 305, in async_config_entry_first_refresh
    if await self.__wrap_async_setup():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 318, in __wrap_async_setup
    await self._async_setup()
  File "/config/custom_components/alfen_wallbox/coordinator.py", line 79, in _async_setup
    if not await self.async_connect():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alfen_wallbox/coordinator.py", line 102, in async_connect
    return await self.device.init()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alfen_wallbox/alfen.py", line 82, in init
    result = await self.get_info()
             ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/alfen_wallbox/alfen.py", line 108, in get_info
    response = await self._session.get(url=self.__get_url(INFO), ssl=self.ssl)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/client.py", line 703, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        req, traces=traces, timeout=real_timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 548, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1056, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1369, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/connector.py", line 1122, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs, sock=sock)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1182, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<2 lines>...
        ssl_shutdown_timeout=ssl_shutdown_timeout)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 1215, in _create_connection_transport
    await waiter
asyncio.exceptions.CancelledError: Home Assistant is stopping
```

the log in alfen:
```
2024-12-31T09:19:19.941Z:INFO:taskWebClient.c:166:Removing previously connected client
2024-12-31T09:19:20.007Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2024-12-31T09:19:21.734Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2024-12-31T09:19:22.027Z:SECURITY:httpd_login.c:155:WebClient ha connected (account: admin)
2024-12-31T09:19:22.097Z:SECURITY:web_functionali:100:Webserver logout client 2
2024-12-31T09:19:22.117Z:INFO:taskWebClient.c:166:Removing previously connected client
2024-12-31T09:19:22.136Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2024-12-31T09:25:57.285Z:INFO:active_lb.c:308:SMt:(0.0 0.0 0.0)A Free:(32.0 32.0 32.0)A ALB:(0.0 0.0 0.0)A
2024-12-31T09:30:59.171Z:USER:taskMaster.c:6045:Temperature: 21.9 C
2024-12-31T09:32:30.820Z:USER:taskMaster.c:6147:Socket #1: L1N=228.2V L2N=0.0V L3N=0.0V L1L2=n/a L2L3=n/a L3L1=n/a 
2024-12-31T09:32:30.832Z:USER:taskMaster.c:6183:Socket #1: I1=0.0A I2=0.0A I3=0.0A P=0.0kW Idc=0.6mA
2024-12-31T09:35:57.257Z:INFO:active_lb.c:308:SMt:(0.0 0.0 0.0)A Free:(32.0 32.0 32.0)A ALB:(0.0 0.0 0.0)A
2024-12-31T09:36:08.878Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2024-12-31T09:36:29.007Z:WARNING:taskWebClient.c:234:Client (fd=2) disconnected (r: -0x7880)
2024-12-31T09:36:29.015Z:INFO:taskWebClient.c:166:Removing previously connected client
2024-12-31T09:36:29.031Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2024-12-31T09:36:29.054Z:WARNING:taskWebClient.c:812:TLS handshake failed (-0x50) for fd=2
2024-12-31T09:36:29.062Z:WARNING:taskWebClient.c:836:Failed to setup WebClient -80
2024-12-31T09:36:30.816Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2024-12-31T09:37:00.964Z:WARNING:taskWebClient.c:234:Client (fd=2) disconnected (r: -0x7880)
2024-12-31T09:37:00.976Z:INFO:taskWebClient.c:166:Removing previously connected client
2024-12-31T09:37:00.988Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2024-12-31T09:37:01.011Z:WARNING:taskWebClient.c:812:TLS handshake failed (-0x50) for fd=2
2024-12-31T09:37:01.023Z:WARNING:taskWebClient.c:836:Failed to setup WebClient -80
2024-12-31T09:37:02.757Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2024-12-31T09:37:32.964Z:WARNING:taskWebClient.c:234:Client (fd=2) disconnected (r: -0x7880)
2024-12-31T09:37:32.972Z:INFO:taskWebClient.c:166:Removing previously connected client
2024-12-31T09:37:33.050Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2024-12-31T09:37:33.078Z:WARNING:taskWebClient.c:812:TLS handshake failed (-0x50) for fd=2
2024-12-31T09:37:33.085Z:WARNING:taskWebClient.c:836:Failed to setup WebClient -80
2024-12-31T09:37:41.027Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2024-12-31T09:38:04.960Z:WARNING:taskWebClient.c:234:Client (fd=2) disconnected (r: -0x7880)
2024-12-31T09:38:04.968Z:INFO:taskWebClient.c:166:Removing previously connected client
2024-12-31T09:38:05.042Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2024-12-31T09:38:05.066Z:WARNING:taskWebClient.c:812:TLS handshake failed (-0x50) for fd=2
2024-12-31T09:38:05.078Z:WARNING:taskWebClient.c:836:Failed to setup WebClient -80
2024-12-31T09:38:41.691Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2024-12-31T09:39:08.949Z:WARNING:taskWebClient.c:234:Client (fd=2) disconnected (r: -0x7880)
2024-12-31T09:39:08.960Z:INFO:taskWebClient.c:166:Removing previously connected client
2024-12-31T09:39:09.000Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2024-12-31T09:39:09.027Z:WARNING:taskWebClient.c:812:TLS handshake failed (-0x50) for fd=2
2024-12-31T09:39:09.035Z:WARNING:taskWebClient.c:836:Failed to setup WebClient -80
2024-12-31T09:40:22.121Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2024-12-31T09:40:44.941Z:WARNING:taskWebClient.c:234:Client (fd=2) disconnected (r: -0x7880)
2024-12-31T09:40:44.949Z:INFO:taskWebClient.c:166:Removing previously connected client
2024-12-31T09:40:45.046Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2024-12-31T09:40:45.074Z:WARNING:taskWebClient.c:812:TLS handshake failed (-0x50) for fd=2
2024-12-31T09:40:45.082Z:WARNING:taskWebClient.c:836:Failed to setup WebClient -80
2024-12-31T09:41:22.351Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2024-12-31T09:41:48.937Z:WARNING:taskWebClient.c:234:Client (fd=2) disconnected (r: -0x7880)
2024-12-31T09:41:48.949Z:INFO:taskWebClient.c:166:Removing previously connected client
2024-12-31T09:41:49.000Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2024-12-31T09:41:49.023Z:WARNING:taskWebClient.c:812:TLS handshake failed (-0x50) for fd=2
2024-12-31T09:41:49.035Z:WARNING:taskWebClient.c:836:Failed to setup WebClient -80
2024-12-31T09:41:50.757Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2024-12-31T09:42:20.933Z:WARNING:taskWebClient.c:234:Client (fd=2) disconnected (r: -0x7880)
2024-12-31T09:42:20.945Z:INFO:taskWebClient.c:166:Removing previously connected client
2024-12-31T09:42:21.035Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2024-12-31T09:42:21.058Z:WARNING:taskWebClient.c:812:TLS handshake failed (-0x50) for fd=2
2024-12-31T09:42:21.070Z:WARNING:taskWebClient.c:836:Failed to setup WebClient -80
2024-12-31T09:42:22.812Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2024-12-31T09:42:52.933Z:WARNING:taskWebClient.c:234:Client (fd=2) disconnected (r: -0x7880)
2024-12-31T09:42:52.941Z:INFO:taskWebClient.c:166:Removing previously connected client
2024-12-31T09:42:52.984Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2024-12-31T09:42:53.007Z:WARNING:taskWebClient.c:812:TLS handshake failed (-0x50) for fd=2
2024-12-31T09:42:53.019Z:WARNING:taskWebClient.c:836:Failed to setup WebClient -80
2024-12-31T09:42:58.417Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2024-12-31T09:43:24.925Z:WARNING:taskWebClient.c:234:Client (fd=2) disconnected (r: -0x7880)
2024-12-31T09:43:24.937Z:INFO:taskWebClient.c:166:Removing previously connected client
2024-12-31T09:43:24.968Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2024-12-31T09:43:24.992Z:WARNING:taskWebClient.c:812:TLS handshake failed (-0x50) for fd=2
2024-12-31T09:43:25.000Z:WARNING:taskWebClient.c:836:Failed to setup WebClient -80
2024-12-31T09:43:58.996Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2024-12-31T09:44:08.773Z:WARNING:taskWebClient.c:234:Client (fd=2) disconnected (r: -0x0)
2024-12-31T09:44:08.785Z:INFO:taskWebClient.c:166:Removing previously connected client
2024-12-31T09:44:08.812Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2024-12-31T09:44:08.839Z:WARNING:taskWebClient.c:812:TLS handshake failed (-0x50) for fd=2
2024-12-31T09:44:08.847Z:WARNING:taskWebClient.c:836:Failed to setup WebClient -80
2024-12-31T09:45:57.230Z:INFO:active_lb.c:308:SMt:(0.0 0.0 0.0)A Free:(32.0 32.0 32.0)A ALB:(0.0 0.0 0.0)A
2024-12-31T09:45:59.730Z:USER:taskMaster.c:6045:Temperature: 22.0 C
2024-12-31T09:47:29.734Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2024-12-31T09:47:30.777Z:USER:taskMaster.c:6147:Socket #1: L1N=227.7V L2N=0.0V L3N=0.0V L1L2=n/a L2L3=n/a L3L1=n/a 
2024-12-31T09:47:30.789Z:USER:taskMaster.c:6183:Socket #1: I1=0.0A I2=0.0A I3=0.0A P=0.0kW Idc=0.6mA
2024-12-31T09:47:39.906Z:WARNING:taskWebClient.c:234:Client (fd=2) disconnected (r: -0x7880)
2024-12-31T09:47:39.917Z:INFO:taskWebClient.c:166:Removing previously connected client
2024-12-31T09:47:39.984Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2024-12-31T09:47:41.703Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2024-12-31T09:47:41.832Z:SECURITY:taskWebClient.c:448:Received unauthorized request, so removing client
2024-12-31T09:47:41.843Z:INFO:taskWebClient.c:166:Removing previously connected client
2024-12-31T09:47:41.949Z:INFO:taskWebServer.c:240:WebServer state BUSY -> AVAILABLE
2024-12-31T09:47:43.667Z:INFO:taskWebServer.c:240:WebServer state AVAILABLE -> BUSY
2024-12-31T09:47:43.972Z:SECURITY:httpd_login.c:155:WebClient ha connected (account: admin)
```

removed device again, installed 2.8.9. reinstalled device...
all ok again.

no more time today to do some testing.

**Comment by fwestenberg** [comment]
When debugging the API, I find the problem with connection is usually all sessions are still occupied. Even though Home Assistant may not be using it anymore. The best solution in my experience is reboot the wallbox (unpower it using the circuit breaker in the fusebox). After the reboot, all sessions are free again and HA can connect again. 

I just created a PR without SSL option, so disabled like before. This seems to be the best working setting.

**Comment by leeyuentuen** [comment]
@fwestenberg i just saw the PR, but there is an conflict. 
I have fix the ssl in my beta2 version.

**Comment by TeddyTBP** [comment]
I can confirm the Wallbox Reset in fuse box worked for me. 

- I disabled transactions in the configuration. 
- disabled 4 wallboxes in HA 
- then fuse 
- then enabled again and now stable 

Pre release is on in the HACS integration for alfen but for now it wont download Beta 4 or 5 somhow it says that these betas are not "The version 2.9.2-beta-5 for this integration can not be used with HACS." And the Pre-Release switch is on.

**Comment by fwestenberg** [comment]
Does 2.9.2-beta-6 work for you? It seems the manifest was not up-to-date with the release version.

**Comment by TeddyTBP** [comment]
Hi, Now the update beta 6 presents itself in the settings but update failsOp 8 jan 2025 om 20:52 heeft fwestenberg ***@***.***> het volgende geschreven:﻿
Does 2.9.2-beta-6 work for you? It seems the manifest was not up-to-date with the release version.

**Comment by fwestenberg** [comment]
For now, can you just copy the folder to your custom components folder?

**Comment by leeyuentuen** [comment]
should be now fix on the latest release 2.9.2-RC, if issue still exists open new issue and explain more what the issue is

**Comment by TeddyTBP** [comment]
Fixed in RC and now all good installed RC after manualy selecting it over 2,8,9
