### ISSUE TITLE
Service call to wallbox.set_current_limit ist not reflected in the UI

### ISSUE THREAD

**Issue by mumpf** [leeyuentuen/alfen_wallbox#31]
Hi,

I am using the service wallbox.set_current_limit in some automations and I see after the next update of all entities a change in sensor.wallbox_active_power_total, but no change in number.wallbox_current_limit. 

For example after setting set_current_limit to 8 I would expect, that wallbox_current_limit changes to 8A, at latest after the entitiy is fetched next time from the device. But nothing happens. Currently I still see wallbox_current_limit displaying 2A, even though I called the service (with value 8) 4 hours ago.

Am I missing something or is this a bug?

Regards,
Waldemar

**Comment by leeyuentuen** [comment]
> service: alfen_wallbox.set_current_limit
> data:
>   entity_id: sensor.wallbox
>   value: 8

did you use something like the code above on your service call?

maybe you can enable the debugging mode and run then again in service and let me see the logs

**Comment by mumpf** [comment]
Yes, I did exactly the above call, with value: 10.

Here is the log:

**2023-08-02` 01:41:50.366 WARNING (MainThread) [py.warnings] /config/custom_components/alfen_wallbox/alfen.py:225: RuntimeWarning: coroutine 'AlfenDevice.set_value' was never awaited
self.set_value("2129_0", limit)**
2023-08-02 02:08:07.639 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.wallbox_status_code is taking over 10 seconds
2023-08-02 02:08:27.633 WARNING (MainThread) [homeassistant.components.sensor] Updating alfen_wallbox sensor took longer than the scheduled update interval 0:00:30
2023-08-02 02:08:57.636 WARNING (MainThread) [homeassistant.components.sensor] Updating alfen_wallbox sensor took longer than the scheduled update interval 0:00:30
2023-08-02 02:08:57.664 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.wallbox_status_code fails
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
return await self._loop.create_connection(*args, **kwargs) # type: ignore[return-value] # noqa
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
transport, protocol = await self._create_connection_transport(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
await waiter
ConnectionAbortedError: SSL handshake is taking longer than 60.0 seconds: aborting the connection
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 695, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 940, in async_device_update
await self.async_update()
File "/config/custom_components/alfen_wallbox/sensor.py", line 862, in async_update
await self._device.async_update()
File "/config/custom_components/alfen_wallbox/alfen.py", line 70, in async_update
await self._do_update()
File "/config/custom_components/alfen_wallbox/alfen.py", line 124, in _do_update
await self.login()
File "/config/custom_components/alfen_wallbox/alfen.py", line 73, in login
response = await self.request(
^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/alfen_wallbox/alfen.py", line 188, in request
response = await self._session.request(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
conn = await self._connector.connect(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
proto = await self._create_connection(req, traces, timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
_, proto = await self._create_direct_connection(req, traces, timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
raise last_exc
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
transp, proto = await self._wrap_create_connection(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.148.17:443 ssl:<ssl.SSLContext object at 0x7f0b14f5b2f0> [None]
2023-08-02 04:33:33.977 WARNING (Thread-6) [pychromecast.socket_client] [Leas JBL Link(192.168.148.123):8009] Heartbeat timeout, resetting connection
2023-08-02 04:33:52.456 ERROR (Thread-6) [pychromecast.socket_client] [Leas JBL Link(192.168.148.123):8009] Failed to connect to service ServiceInfo(type='host', data=('192.168.148.123', 8009)), retrying in 5.0s
2023-08-02 09:38:59.487 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Force update failed, falling back to cached: Request timeout. - Request timeout.
Traceback (most recent call last):
File "/config/custom_components/kia_uvo/coordinator.py", line 126, in _async_update_data
await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 103, in check_and_force_update_vehicles
self.update_vehicle_with_cached_state(vehicle_id)
File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 80, in update_vehicle_with_cached_state
self.api.update_vehicle_with_cached_state(self.token, vehicle)
File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 306, in update_vehicle_with_cached_state
state = self._get_cached_vehicle_state(token, vehicle)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 720, in _get_cached_vehicle_state
_check_response_for_errors(response)
File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 113, in _check_response_for_errors
raise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.RequestTimeoutError: Request timeout. - Request timeout.
2023-08-02 10:49:09.042 WARNING (MainThread) [homeassistant.helpers.entity] Update of select.wallbox_solar_charging_mode is taking over 10 seconds
2023-08-02 10:49:29.040 WARNING (MainThread) [homeassistant.components.select] Updating alfen_wallbox select took longer than the scheduled update interval 0:00:30
2023-08-02 10:49:59.041 WARNING (MainThread) [homeassistant.components.select] Updating alfen_wallbox select took longer than the scheduled update interval 0:00:30
2023-08-02 10:49:59.054 ERROR (MainThread) [homeassistant.helpers.entity] Update for select.wallbox_solar_charging_mode fails
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 980, in _wrap_create_connection
return await self._loop.create_connection(*args, **kwargs) # type: ignore[return-value] # noqa
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
transport, protocol = await self._create_connection_transport(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
await waiter
ConnectionAbortedError: SSL handshake is taking longer than 60.0 seconds: aborting the connection
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 695, in async_update_ha_state
await self.async_device_update()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 940, in async_device_update
await self.async_update()
File "/config/custom_components/alfen_wallbox/select.py", line 272, in async_update
await self._device.async_update()
File "/config/custom_components/alfen_wallbox/alfen.py", line 70, in async_update
await self._do_update()
File "/config/custom_components/alfen_wallbox/alfen.py", line 124, in _do_update
await self.login()
File "/config/custom_components/alfen_wallbox/alfen.py", line 73, in login
response = await self.request(
^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/alfen_wallbox/alfen.py", line 188, in request
response = await self._session.request(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
conn = await self._connector.connect(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
proto = await self._create_connection(req, traces, timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
_, proto = await self._create_direct_connection(req, traces, timeout)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1209, in _create_direct_connection
raise last_exc
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1178, in _create_direct_connection
transp, proto = await self._wrap_create_connection(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 988, in _wrap_create_connection
raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.148.17:443 ssl:<ssl.SSLContext object at 0x7f0b14f5b2f0> [None]

Main problem seems to be the first line.

Thanks for your help,
Waldemar

**Comment by leeyuentuen** [comment]
i need to test it out. but on the first view it seems that there is multiple connection active. i mean maybe there is a my eve app active and home assistant instance active. i know from the past that alfen only allowed to have 1 active connection. otherwise you will get timeout errors on the call

**Comment by leeyuentuen** [comment]
i see the issue, i'll take a look on it

**Comment by leeyuentuen** [comment]
@mumpf can you take a look at this beta version if it solves the service call issue?
https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.4.1

also, there is an example code added in case your CP is called "wallbox" and you have only one CP, then the example code should fill the correct entity_id and an example value
![image](https://github.com/leeyuentuen/alfen_wallbox/assets/1487966/ac2e4ff6-4186-479a-95fa-204a29b5c8c4)

**Comment by leeyuentuen** [comment]
btw, there was an issue will all the services call. This was added by myself, but at the beginning where we can't change the value on the GUI, but when it was possible on the GUI, I didn't use the services call anymore, so didn't notice this issue

**Comment by amurray81** [comment]
Just came on to look at this same issue. 

Weeks ago I set up an automation to change the current limit in preparation for my solar installation which is happening today. I tested it then and it worked.

Now when I run the automation nothing happens. I had to update the entity as it had changed in one of the previous updated. I did not create the entity with "2"

![image](https://github.com/leeyuentuen/alfen_wallbox/assets/130550172/1b3e466f-c4e5-4c73-8086-806894cb6473)
![image](https://github.com/leeyuentuen/alfen_wallbox/assets/130550172/2b187778-57a3-45c8-ba12-fa96187f1c0d)
![image](https://github.com/leeyuentuen/alfen_wallbox/assets/130550172/c2f3393e-aeb8-4a5a-82fa-208181fa3e96)

**Comment by leeyuentuen** [comment]
@amurray81 

the 2 came after update of the latest public release ([2.3.2](https://github.com/leeyuentuen/alfen_wallbox/releases/tag/2.3.2))

the fastest way to fix them is to remove the current wall box and re-add them, normally the entity-id will be back like the previous one

**Comment by amurray81** [comment]
@leeyuentuen thank you

As above I can confirm the automation works again on 2.41 release

**Comment by leeyuentuen** [comment]
> @leeyuentuen thank you
> 
> As above I can confirm the automation works again on 2.41 release

I will mark it as tested, but let me see if @mumpf  also solved the issue

**Comment by mumpf** [comment]
Thank you for your immediate help! It works with 2.4.1.

Regards,
Waldemar

**Comment by leeyuentuen** [comment]
great, i'll put them on ready for release
